version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./tests:/app/tests
    env_file:
      - .env
    environment:
      - GOOGLE_GEMINI_API_KEY
      - OPENAI_API_KEY
      - COHERE_API_KEY
      - DEBUG
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  test:
    build: .
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    env_file:
      - .env
    environment:
      - GOOGLE_GEMINI_API_KEY
      - OPENAI_API_KEY
      - COHERE_API_KEY
      - DEBUG
    command: pytest tests/ -v
    profiles:
      - test
